#beautiful soup,pandas,numpy,plotly,matplotlib,seaborn

# Numpy

#numpy is a general purpose array processing package.It provide a high performance multidimensional array object,and tools for working with these arrays.It is the fundamental package for scientific computing with python.
#besides its obvious scientific uses,Numpy can also be used as an efficient multi-dimensional container of generic data
#using for working with arrays
#it also has functions for working in domain of linear algebra,fourier transform,and matrices
#numpy was created in 2005 by travis oliphant
#itis an open source project and you can use it freely
#Numpy is the core library for scientific computing in pyton
#numpy main object is the multidimensional array.
#It is a table of elements (usually number),all of the type,indexed by a tuple of positive integers.
#In Numpy dimensions are called axes


#dijango web framework for python

# pandas

#in computer programming pandas is a software library written for the python programming language for data manipulation and data anlysis.
#in particular it offers data structures and operations for manipulatng numerical tables and time series
#it is free software released under the three clauses BSD license 

# Matplotlib

#It is comprehensive library for creating static,animated,interactive,visualizations in python
#Matplotlib makes easy things easy and hard things possible
#create ,develop publication quality plots with just a few lines of code
#It uses interactive figure that can zoom,pan,update,rotate,etc.

# math used for mathematical library #squard root,addition, substraction #and perform mathematical #operations


# plotly

#plotly python is an open source graphing library
#plotlys python graphing library makes interactive(drag it,rotate it,zoom it,click on it not only display o/p),publication-quality graphs.
#e.g.of how to make line-plots,area charts,bar charts,scatter plot,error bars,box plots,histogram,heatmaps,subplots,multiple-axes,polar charts and bubble charts

# seaborn

#data visulization library same as matplotlib
#seaborn is a high data visualization library based on matplotlib
#It provides a high level interface for drawing attractive and informative statistical grahics.
#It builds on top of matplotlib and integrates closely with pandas data structures.
#seaborn helps you explore and understand your data

# Beautiful soup

#beautiful soup is a python library for getting data out of html,XML,and other markup language.
#say you have found some webpages that display data relevant to your research,such as date or address information,but that do not provide any way of downloading the data directly.Beautiful soup helps you pull particular content from a webpage,remove the html markup and save the information. It is a tool for web scraping that helps you  clean up and parse the documents you have pulled down from the web 

In [ ]:
#conda install numpy
#pip install numpy

#Numpy vs list
#adavantages of numpy over list
1.less memory
2.fast
3.convenient
#Numpy is a fundamental package for scientific computing in python
#it contains n dimensional array object
#it has tools to integrating the c ,c++ and it is very useful to performing the linear algebra,fourier transform and random number capability etc.

In [ ]:
#data type desciption
1.bool--->boolean (true false)stored as a byte
2.int---->default integer type/same as C long:normally either int64 or int32)
3.intc---->Identical to C int (normally int32 or int64)
4.intp
5.int8
6.int16
7.int32
8.int64
9.uint8
10.uint16
11.uint32
12.float
13.float16
14.float32
15.float64
complex
complex64
complex128

In [ ]:
what are methods we can apply on array
all()
any()
take()
put()
apply_along_axis()
apply_over_axes()
argmin()
argmax()
nanargmin()
nanargmax()
amax()
amin()
insert()
delete()
append()
around()
flip()
fliplr()
flipud()
triu()
tril()
tri()
empty()
empty_like()
zeros()
zeros_like()
ones()
ones_like()
full_like()
diag()
diagflat()
diag_indices()
asmatrix()
bmat()
eye()
roll()
identify()
arange()
place()
compress()
rot90()
extract()
tile()
reshape()
ravel()
isinf()
isrealobj()
isscalar()
isposinf()
iscomplex()
isneginf()
isnan()
iscomplexobj()
isreal()
isfinite()
isfortran()
exp()
exp2()
fix()
hypot()
absolute()
cell()
floor()
degrees()
radians()
npv()
fv()
pv()
power()
float_power
log
log1
log2
log10
dot
vdot
trunc
divide
true_divide()
floor_divide()
random.rand()
random.randn()
ndarray.flat()
expm1()
bincount()
rint()
equal()
not_equal
less()
greater
greater_equal()
square
cbrt
prod
logical_or
logical_and
logical_not
logical_xor
array_equal
array_eualv
tan
cos
sin
sinh
cosh
tanh
arcsin
arccos
arctan
arctan2


In [8]:
import numpy as np

In [10]:
a=np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [11]:
a.reshape

<function ndarray.reshape>

In [13]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
a.ndim

1

In [20]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
a.dtype.name

'int32'

In [17]:
a.itemsize

4

In [18]:
a.size

25

In [19]:
a.shape

(25,)

In [24]:
a[1:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a[1:3]

array([1, 2])

In [22]:
a[1:5]

array([1, 2, 3, 4])

In [25]:
a[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24])

In [26]:
a[8]

8

In [27]:
a[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
a[:-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [29]:
a[::-2]

array([24, 22, 20, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

In [30]:
a[::-1]

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,
        7,  6,  5,  4,  3,  2,  1,  0])

In [31]:
a[::-3]

array([24, 21, 18, 15, 12,  9,  6,  3,  0])

In [34]:
x=a.reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
x[2]

array([10, 11, 12, 13, 14])

In [44]:
x[4]

array([20, 21, 22, 23, 24])

In [42]:
x[2:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
x[:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
x[:5]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
a[2]

2

In [36]:
x[:2,:3]#1st for row and 2nd para for column

array([[0, 1, 2],
       [5, 6, 7]])

In [37]:
x[:3,:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [38]:
x[2:5,:4]

array([[10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

# pandas

In [ ]:
#it is a python package providing fast, flexible and experssive data structures designed
#pandas is top of numpy
#pandas is build on two data structures 1)series 2)dataframe
1)series:it is one dimensional labelled array capable of holding any datatype
    #series(data,index=index)
    #series will be created in array ,dictm,scalar value or constant

In [1]:
#creating a series from ndarray
#import the pandas library and aliasing as pd
import pandas as pd
import numpy as np

In [4]:
test=np.array(['s','o','c','i','a','l'])
test
s=pd.Series(test)
s

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

0    s
1    o
2    c
3    i
4    a
5    l
dtype: object

In [ ]:
#pandas series is a one dimensional labeled array capable of holding data of any type(integer,string,float,python objects,etc)the axis labels are collectively called index.pandas series is nothing but a column in an excel sheet.

In [5]:
s=pd.Series(test)
s

<IPython.core.display.Javascript object>

0    s
1    o
2    c
3    i
4    a
5    l
dtype: object

In [6]:
x=2
y=3
z=x+y
z

5

In [8]:
test=np.array(['s','o','c','i','a','l'])
#indexing in pandas means simply selecting particular rows and columns of data from a DataFrame.
#Indexing could mean selecting all the rows and  some of columns,some of the rows and all of the columns,or some of each
#of the rows and columns .Indexing can also be known as subset selection.
s=pd.Series(test,index=[1,2,3,4,5,6])
s

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

1    s
2    o
3    c
4    i
5    a
6    l
dtype: object

In [12]:
#Dict
#dictionary keys are taken in sorted order to construct index
test={'a':1,'d':3,'c':2}
s=pd.Series(test)
s

<IPython.core.display.Javascript object>

a    1
d    3
c    2
dtype: int64

In [13]:
#Scalar
#if the data have repeated value then we have to match the index(so index value will be repeating)
x=pd.Series(2,index=[0,1,2])
x

<IPython.core.display.Javascript object>

0    2
1    2
2    2
dtype: int64

In [23]:
#Series Indexing
s=pd.Series([1,2,3,4,5,6],index=['s','o','c','i','a','l'])
s

s    1
o    2
c    3
i    4
a    5
l    6
dtype: int64

In [17]:
s['s']

1

In [18]:
s['o']

2

In [19]:
s[3]

4

In [20]:
s[0]

1

In [21]:
s['c']

3

In [22]:
import pandas as pd

# In pandas we need to remember few things those are:
1)sets
2)Data Frame
3)Loading Data from different file formats
4)Data Manipulation

# 1)Series
Series is a one-dimensional labeled array capable of holding data of any type(integer,string,float,python objects,etc.)
The axis labels are collectively called index.
A series can be created using various inputs like
----1)Array
----2)Dict


# create an Empty series

In [30]:
# import pandas as pd
s=pd.Series()
s

C:\logs\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  


Series([], dtype: float64)

# Create a Series from ndarray

In [28]:
import numpy as np
data=np.array(['a','b','c','d'])
data

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [29]:
series=pd.Series(data)
series

0    a
1    b
2    c
3    d
dtype: object

In [34]:
#Create a series from ndarray and define index
import numpy as np
data=np.array(['a','b','c','d'])
import pandas as pd
series=pd.Series(data,index=[100,101,102,103])
series

100    a
101    b
102    c
103    d
dtype: object

In [35]:
#create a Series from dict
data={'a':0.,'b':1.,'c':2.}
series=pd.Series(data)
series

a    0.0
b    1.0
c    2.0
dtype: float64

In [36]:
#Create a Series from dict and use the radom index for output
data={'a':0.,'b':1.,'c':2.}
import pandas as pd
series=pd.Series(data,index=['b','c','d','a'])
series

b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64

# Accessing data from series with position (index)

In [37]:
import pandas as pd
series=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [38]:
#by using the index calling first element
series[0]

1

In [39]:
#by using the index calling last element
series[-1]

5

In [40]:
series[:1]

a    1
dtype: int64

In [42]:
#by using the index calling second to last elemnt
series[1:]

b    2
c    3
d    4
e    5
dtype: int64

In [43]:
#by using the index calling forth to first element
series[:4]

a    1
b    2
c    3
d    4
dtype: int64

In [46]:
#retrieve data using label(index)
series=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [47]:
series['a']

1

In [48]:
series[['a','d','e']]

a    1
d    4
e    5
dtype: int64

In [49]:
series[1]

2

In [50]:
series[0]

1

# 2)Data Frame
A DataFrame is a two dimensional data structure,i.e.data is alligned in a tabular fashion in rows and columns

# Features of DataFrame

In [ ]:
1)potentially columns are of different types
2)size-mutable
3)Labeled axes(rows and columns)
4)Can perform Arithmetic operations on rows and columns

# How to Create data Frame by using variable
storing dictonary into variable

In [51]:
import pandas as pd

In [52]:
web={'day':[1,2,3,4,5,6],'visitors':[1000,2000,3000,2509,5125,1256],'Bounce_Rate':[10,20,30,14,50,6]}
web

{'day': [1, 2, 3, 4, 5, 6],
 'visitors': [1000, 2000, 3000, 2509, 5125, 1256],
 'Bounce_Rate': [10, 20, 30, 14, 50, 6]}

In [53]:
#By using the pandas converting Dict into the DataFrame
df=pd.DataFrame(web)
df

day  visitors  Bounce_Rate
0    1      1000           10
1    2      2000           20
2    3      3000           30
3    4      2509           14
4    5      5125           50
5    6      1256            6

# pandas operations
1)slicing the dataframe
2)changing the index
3)Data conversion
4)joining and merging
5)changing the column headers

# 1)slicing

In [55]:

import pandas as pd
Bank={'year':[2001,2002,2003,2004,2005,2006,2007],'Int_rate':[2,3,2,2,1,3,6],'US_GDP_Thousands':[50,55,65,55,60,65,54]}
df=pd.DataFrame(Bank)
df

year  Int_rate  US_GDP_Thousands
0  2001         2                50
1  2002         3                55
2  2003         2                65
3  2004         2                55
4  2005         1                60
5  2006         3                65
6  2007         6                54

In [57]:
#Head
#Default head method displaying first five rows rom data frame
#default it going to prit starting 5 rows
df.head()

year  Int_rate  US_GDP_Thousands
0  2001         2                50
1  2002         3                55
2  2003         2                65
3  2004         2                55
4  2005         1                60

In [58]:
#If I want to print starting 3 rows then I passing value to the head
df.head(3)

year  Int_rate  US_GDP_Thousands
0  2001         2                50
1  2002         3                55
2  2003         2                65

# Tail

In [59]:
#Default tail method displaying last five I am going to use tail
df.tail()

year  Int_rate  US_GDP_Thousands
2  2003         2                65
3  2004         2                55
4  2005         1                60
5  2006         3                65
6  2007         6                54

In [60]:
df.tail(3)

year  Int_rate  US_GDP_Thousands
4  2005         1                60
5  2006         3                65
6  2007         6                54

# Merging

In [69]:
#Here we are going to take two data frames
df1=pd.DataFrame({'HPI':[80,90,70,60],'rate':[2,2,1,3],'GDP':[50,55,65,55]})
df1

HPI  rate  GDP
0   80     2   50
1   90     2   55
2   70     1   65
3   60     3   55

In [70]:
df2=pd.DataFrame({'HPI':[50,90,70,60],'rate':[2,1,2,3],'GDP':[50,55,65,55]})
df2

HPI  rate  GDP
0   50     2   50
1   90     1   55
2   70     2   65
3   60     3   55

In [71]:
df5=pd.merge(df1,df2,on='rate')
df5

HPI_x  rate  GDP_x  HPI_y  GDP_y
0     80     2     50     50     50
1     80     2     50     70     65
2     90     2     55     50     50
3     90     2     55     70     65
4     70     1     65     90     55
5     60     3     55     60     55

In [72]:
df3=pd.merge(df1,df2)
df3

HPI  rate  GDP
0   60     3   55

In [ ]:
#JOINING
Based on the index value it going to add
Based on the first data Frame,it going to check the index and joing the values


In [73]:
df6=pd.DataFrame({'HPI':[80,90,70,60],'rate':[2,1,2,3]})
df6

HPI  rate
0   80     2
1   90     1
2   70     2
3   60     3

In [74]:
df7=pd.DataFrame({'CPI':[80,90,70],'Years':[2,1,5]})
df7

CPI  Years
0   80      2
1   90      1
2   70      5

In [77]:
df=df7.join(df6)
df

CPI  Years  HPI  rate
0   80      2   80     2
1   90      1   90     1
2   70      5   70     2

In [79]:
df=df6.join(df7)
df

HPI  rate   CPI  Years
0   80     2  80.0    2.0
1   90     1  90.0    1.0
2   70     2  70.0    5.0
3   60     3   NaN    NaN

# 2)changing the index and column headers

# changing the index

In [81]:
df12=pd.DataFrame({'Day':[1,2,3,4,5,6],'visitors':[1000,2000,3000,2504,5125,1256],'Bounce_Rate':[10,20,30,14,50,6]})
df12 

Day  visitors  Bounce_Rate
0    1      1000           10
1    2      2000           20
2    3      3000           30
3    4      2504           14
4    5      5125           50
5    6      1256            6

In [82]:
df12.set_index("visitors",inplace=True)
df12

Day  Bounce_Rate
visitors                  
1000        1           10
2000        2           20
3000        3           30
2504        4           14
5125        5           50
1256        6            6

In [83]:
#Changing the column Name
df13=df12.rename(columns={'Day':"No of Days"})
df13

No of Days  Bounce_Rate
visitors                         
1000               1           10
2000               2           20
3000               3           30
2504               4           14
5125               5           50
1256               6            6

In [84]:
#Concatenation
df14=pd.DataFrame({'HPI':[80,90,70,60],'Int_rate':[2,1,2,3]},index=[2001,2002,2004,2005])
df14

HPI  Int_rate
2001   80         2
2002   90         1
2004   70         2
2005   60         3

In [86]:
df15=pd.DataFrame({'HPI':[80,90,70,60],'Years':[2,1,2,3],'Int_rate':[2,1,2,3]},index=[2002,2006,2007,2008])
df15

HPI  Years  Int_rate
2002   80      2         2
2006   90      1         1
2007   70      2         2
2008   60      3         3

In [87]:
df15=pd.DataFrame({'HPI':[80,90,70,60],'Years':[2,1,2,3],'Int_rate':[2,1,2,3]},index=[2001,2002,2004,2005])
df15

HPI  Years  Int_rate
2001   80      2         2
2002   90      1         1
2004   70      2         2
2005   60      3         3

In [88]:
df17=pd.concat([df14,df15],sort=True)
df17

HPI  Int_rate  Years
2001   80         2    NaN
2002   90         1    NaN
2004   70         2    NaN
2005   60         3    NaN
2001   80         2    2.0
2002   90         1    1.0
2004   70         2    2.0
2005   60         3    3.0

# How to load(read the file)in the pandas

In [91]:
df18=pd.read_csv(r"C:\Users\SAGAR\Documents\ashwini\latest_project\avishkar\Data.csv")
df18

Unnamed: 0     budget  \
0              0  237000000   
1              1  300000000   
2              2  245000000   
3              3  250000000   
4              4  260000000   
...          ...        ...   
4798        4798     220000   
4799        4799       9000   
4800        4800          0   
4801        4801          0   
4802        4802          0   

                                                 genres  \
0     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...                                                 ...   
4798  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4799  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
4800  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4801                                                 []   
4802                [{"id": 99, "name": "Documentary"}]   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995   
1          http://disney.go.com/disneypictures/pirates/     285   
2           http://www.sonypictures.com/movies/spectre/  206647   
3                    http://www.thedarkknightrises.com/   49026   
4                  http://movies.disney.com/john-carter   49529   
...                                                 ...     ...   
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                               keywords original_language  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4     [{"id": 818, "name": "based on novel"}, {"id":...                en   
...                                                 ...               ...   
4798  [{"id": 5616, "name": "united states\u2013mexi...                es   
4799                                                 []                en   
4800  [{"id": 248, "name": "date"}, {"id": 699, "nam...                en   
4801                                                 []                en   
4802  [{"id": 1523, "name": "obsession"}, {"id": 224...                en   

                                original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
4798                               El Mariachi   
4799                                 Newlyweds   
4800                 Signed, Sealed, Delivered   
4801                          Shanghai Calling   
4802                         My Date with Drew   

                                               overview  popularity  ...  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577  ...   
1     Captain Barbossa, long believed to be dead, ha...  139.082615  ...   
2     A cryptic message from Bond’s past sends him o...  107.376788  ...   
3     Following the death of District Attorney Harve...  112.312950  ...   
4     John Carter is a war-weary, former military ca...   43.926995  ...   
...                                                 ...         ...  ...   
4798  El Mariachi just wants to play his guitar and ...   14.